### ISSUE TITLE
createto causes an internal Server Error

### ISSUE THREAD

**Issue by DJPlaya** [Arkarr/ASteambot#1]
I know this is still in Alpha but i feel like reporting this

```
> createto STEAM_0:0:56114639

Unhandled Exception: System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at SteamTrade.SteamWeb.Request(String url, String method, NameValueCollection data, Boolean ajax, String referer, Boolean
 fetchError)
   at SteamTrade.SteamWeb.Fetch(String url, String method, NameValueCollection data, Boolean ajax, String referer, Boolean f
etchError)
   at SteamTrade.TradeOffer.OfferSession.Request(String url, NameValueCollection data, String referer, String tradeOfferId,
String& newTradeOfferId)
   at SteamTrade.TradeOffer.OfferSession.SendTradeOffer(String message, SteamID otherSteamId, TradeStatus status, String& ne
wTradeOfferId)
   at SteamTrade.TradeOffer.TradeOffer.Send(String& offerId, String message)
   at ASteambot.Bot.CreateTradeOffer(String otherSteamID)
   at ASteambot.Manager.CreateTradeOffer(String[] args)
   at ASteambot.Manager.Command(String command)
   at ASteambot.Program.Main(String[] args)
```

**Comment by Arkarr** [comment]
Woups, "createto" command isn't really necessary, it's for debug stuff.
It will try to create a trade offer with the first item from the game TF2 (app id 440).
If you have no items (make sure they are tradeble) from this game, you will create a empty trade offer, and the steam server will refuse to create the server and return the error code 500.

**Comment by Arkarr** [comment]
Means what ?

**Comment by DJPlaya** [comment]
I just remembered that with the old bot it crashed when someone tried to trade items with an amount

**Comment by Arkarr** [comment]
Oh.. I'll look at that now.
