### ISSUE TITLE
Unable to Login, Captcha Issue

### ISSUE THREAD

**Issue by samdisk11** [Arkarr/ASteambot#32]
i cant login, as it asks me to visit a captcha URL, and when i input what it says, it asks me to try again with a NEW url.

HELP!!!!!!!!!!!

**Comment by samdisk11** [comment]
and now it just decides to crash. here is the log files

**Comment by samdisk11** [comment]
*************************
11/11/2020 2:27:47 PM (Version V13.1 - PUBLIC) LINUX : NO
*************************
-2147024893 - System.Private.CoreLib
Microsoft.Win32.SafeHandles.SafeFileHandle ValidateFileHandle(Microsoft.Win32.SafeHandles.SafeFileHandle)


Could not find a part of the path 'C:\Users\admin\Desktop\win-x64\auth\sentry-craggy144.bin'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at ASteambot.Bot.OnMachineAuth(UpdateMachineAuthCallback callback) in C:\Users\Arkarr\Documents\GitHub\ASteambot\SOURCE\ASteambot\Bot.cs:line 1171
   at SteamKit2.Internal.Callback`1.Run(Object callback)
   at SteamKit2.CallbackManager.<>c__DisplayClass10_0.<Handle>b__1(CallbackBase callback)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at SteamKit2.CallbackManager.Handle(ICallbackMsg call)
   at SteamKit2.CallbackManager.RunWaitAllCallbacks(TimeSpan timeout)
   at ASteambot.Bot.Run() in C:\Users\Arkarr\Documents\GitHub\ASteambot\SOURCE\ASteambot\Bot.cs:line 878
   at ASteambot.Manager.Start() in C:\Users\Arkarr\Documents\GitHub\ASteambot\SOURCE\ASteambot\Manager.cs:line 56
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()


*************************
11/11/2020 2:28:50 PM (Version V13.1 - PUBLIC) LINUX : NO
*************************
-2147024893 - System.Private.CoreLib
Microsoft.Win32.SafeHandles.SafeFileHandle ValidateFileHandle(Microsoft.Win32.SafeHandles.SafeFileHandle)


Could not find a part of the path 'C:\Users\admin\Desktop\win-x64\auth\sentry-craggy144.bin'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at ASteambot.Bot.OnMachineAuth(UpdateMachineAuthCallback callback) in C:\Users\Arkarr\Documents\GitHub\ASteambot\SOURCE\ASteambot\Bot.cs:line 1171
   at SteamKit2.Internal.Callback`1.Run(Object callback)
   at SteamKit2.CallbackManager.<>c__DisplayClass10_0.<Handle>b__1(CallbackBase callback)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at SteamKit2.CallbackManager.Handle(ICallbackMsg call)
   at SteamKit2.CallbackManager.RunWaitAllCallbacks(TimeSpan timeout)
   at ASteambot.Bot.Run() in C:\Users\Arkarr\Documents\GitHub\ASteambot\SOURCE\ASteambot\Bot.cs:line 878
   at ASteambot.Manager.Start() in C:\Users\Arkarr\Documents\GitHub\ASteambot\SOURCE\ASteambot\Manager.cs:line 56
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by Arkarr** [comment]
Does your bot account have steamguard enabled ? Email ?

**Comment by samdisk11** [comment]
steamguard desktop authenticator, also ouch.

**Comment by Arkarr** [comment]
You may reopen this issue if you still have problems with V13.2, for now, I'll close it.
