### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MissXecutioner** [Arkarr/ASteambot#33]
Error while fetching country code. Assumed 'en'. Details here :
Faulty country >>> Turkey
Send to Arkarr please!
System.Globalization.CultureNotFoundException: Culture is not supported. (Parameter 'culture')
4096 (0x1000) is an invalid culture identifier.
   at System.Globalization.CultureData.GetCultureData(Int32 culture, Boolean bUseUserOverride)
   at System.Globalization.RegionInfo..ctor(Int32 culture)
   at ASteambot.Translation.CountryCode.<>c.<GetCountryCode>b__0_0(CultureInfo x) in C:\Users\Arkarr\Documents\GitHub\ASteambot\SOURCE\ASteambot\Translation\CountryCode.cs:line 27
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at ASteambot.Translation.CountryCode.GetCountryCode(Infos sp) in C:\Users\Arkarr\Documents\GitHub\ASteambot\SOURCE\ASteambot\Translation\CountryCode.cs:line 28

**Comment by Arkarr** [comment]
Thanks for the error report.
This won't impact ASteambot, it's a warning. A note for myself if you will. I'll update ASteambot ASAP and remove this.,
