### ISSUE TITLE
Error v2 (Windows)

### ISSUE THREAD

**Issue by MissXecutioner** [Arkarr/ASteambot#34]
*************************
14.4.2021 15:18:12 (Version V13.6 - PUBLIC) LINUX : NO
*************************
-2146233079 - System.Net.Requests
System.Net.WebResponse GetResponse()

The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at SteamTrade.SteamWebCustom.Request(String url, String method, NameValueCollection data, Boolean ajax, String referer, Boolean fetchError) in C:\Users\Arkarr\Documents\GitHub\ASteambot\SOURCE\ASteambot\SteamTrade\SteamWebCustom.cs:line 191
   at SteamTrade.SteamWebCustom.Fetch(String url, String method, NameValueCollection data, Boolean ajax, String referer, Boolean fetchError) in C:\Users\Arkarr\Documents\GitHub\ASteambot\SOURCE\ASteambot\SteamTrade\SteamWebCustom.cs:line 88
   at SteamTrade.TradeOffer.OfferSession.Request(String url, NameValueCollection data, String referer, String tradeOfferId, String& newTradeOfferId) in C:\Users\Arkarr\Documents\GitHub\ASteambot\SOURCE\ASteambot\SteamTrade\TradeOffer\OfferSession.cs:line 238
   at SteamTrade.TradeOffer.OfferSession.SendTradeOffer(String message, SteamID otherSteamId, TradeStatus status, String& newTradeOfferId) in C:\Users\Arkarr\Documents\GitHub\ASteambot\SOURCE\ASteambot\SteamTrade\TradeOffer\OfferSession.cs:line 200
   at SteamTrade.TradeOffer.TradeOffer.Send(String& offerId, String message) in C:\Users\Arkarr\Documents\GitHub\ASteambot\SOURCE\ASteambot\SteamTrade\TradeOffer\TradeOffer.cs:line 134
   at ASteambot.Networking.HandleMessage.CreateTradeOffer(Bot bot, GameServerRequest gsr) in C:\Users\Arkarr\Documents\GitHub\ASteambot\SOURCE\ASteambot\Networking\TCPInterface\HandleMessage.cs:line 466
   at ASteambot.Networking.HandleMessage.Execute(Bot bot, GameServerRequest gsr) in C:\Users\Arkarr\Documents\GitHub\ASteambot\SOURCE\ASteambot\Networking\TCPInterface\HandleMessage.cs:line 53

**Comment by Arkarr** [comment]
Hello,

Can you tell me how you managed to get this error ?
Right, I can only assume that's because you are trying to trade too fast. Too many trade request has been made through / to the bot, hence Steam Network timing you out ( --> (500) Internal Server Error)
