### ISSUE TITLE
ASteambot crashed :(

### ISSUE THREAD

**Issue by MissXecutioner** [Arkarr/ASteambot#38]
![image](https://user-images.githubusercontent.com/73059032/124106882-56f32d80-da6d-11eb-9801-0da14d25f8d3.png)
```
*************************
7/1/2021 3:01:00 AM (Version V13.6 - PUBLIC) LINUX : NO
*************************
-2147467259 - System.Net.Sockets
Void UpdateStatusAfterSocketErrorAndThrowException(System.Net.Sockets.SocketError, System.String)


An existing connection was forcibly closed by the remote host.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.EndAccept(Byte[]& buffer, Int32& bytesTransferred, IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndAccept(IAsyncResult asyncResult)
   at ASteambot.Networking.TCPInterface.AcceptCallback(IAsyncResult ar) in C:\Users\Arkarr\Documents\GitHub\ASteambot\SOURCE\ASteambot\Networking\TCPInterface\TCPInterface.cs:line 131
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)
```

**Comment by Arkarr** [comment]
Ha weird... Was you able to reproduce the crash ? Normally, this case is handled.

**Comment by MissXecutioner** [comment]
Yes, I still get crashes over and over again.

**Comment by MissXecutioner** [comment]
In addition, it automatically unfriends people.

**Comment by Arkarr** [comment]
Can you add me on Steam ? I'd like to debug with you.

**Comment by MissXecutioner** [comment]
I already added you. Miss Xecutioner is my steam name.
