### ISSUE TITLE
Scan error

### ISSUE THREAD

**Issue by MissXecutioner** [Arkarr/ASteambot#42]
Error while inventory scan :
Exception: System.Net.WebException: Resource temporarily unavailable Resource temporarily unavailable
 ---> System.Net.Http.HttpRequestException: Resource temporarily unavailable
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at SteamTrade.SteamWebCustom.Request(String url, String method, NameValueCollection data, Boolean ajax, String referer, Boolean fetchError) in C:\Users\Arkarr\Documents\GitHub\ASteambot\SOURCE\ASteambot\SteamTrade\SteamWebCustom.cs:line 147
   at SteamTrade.SteamWebCustom.Fetch(String url, String method, NameValueCollection data, Boolean ajax, String referer, Boolean fetchError) in C:\Users\Arkarr\Documents\GitHub\ASteambot\SOURCE\ASteambot\SteamTrade\SteamWebCustom.cs:line 73
   at SteamTrade.GenericInventory.loadImplementation(Int32 appid, IEnumerable`1 contextIds, SteamID steamid) in C:\Users\Arkarr\Documents\GitHub\ASteambot\SOURCE\ASteambot\SteamTrade\GenericInventory.cs:line 194
For more infos; visit this link :
http://steamcommunity.com/profiles/76561198971336416/inventory/json/730/2/

**Comment by MissXecutioner** [comment]
System.NullReferenceException: Object reference not set to an instance of an object.
   at ASteambot.Networking.HandleMessage.CreateTradeOffer(Bot bot, GameServerRequest gsr) in C:\Users\Arkarr\Documents\GitHub\ASteambot\SOURCE\ASteambot\Networking\TCPInterface\HandleMessage.cs:line 498
   at ASteambot.Networking.HandleMessage.Execute(Bot bot, GameServerRequest gsr) in C:\Users\Arkarr\Documents\GitHub\ASteambot\SOURCE\ASteambot\Networking\TCPInterface\HandleMessage.cs:line 53
Crashing while executing net code 7 !
Full detail message [MAY CONTAIN SENSITIVE INFOS] :
SRV ID : 1 MDL ID: 1
STEAM_1:0:448166369/23138827677,23111305080,23088468621,23088467688,23088466188,23088462338/NULL/16.07
Line number : 498
SEND LOGS TO ARKARR (see generated log file) !
Log file (SEND_TO_ARKARR.log) generated ! Send it to Arkarr !!

**Comment by Arkarr** [comment]
The inventory of the target is private. But ASteambot shouldn't crash. I'll check about that right now.

**Comment by Kerimengit** [comment]
Hello, I also encountered this problem and as I understand it, the bot is abandoned and there are no plans to fix its errors? If so, it's a pity.

**Comment by Arkarr** [comment]
It is not, I just have so much on my hands. I'll try to schedule to upgrade, improve and fix ASteambot
